export type NigeriaLocation = {
  state: string;
  areas: string[];
};

export const nigeriaLocations: NigeriaLocation[] = [
  { state: "Abia", areas: ["Aba North", "Aba South", "Arochukwu", "Bende", "Ikwuano", "Isiala Ngwa North", "Isiala Ngwa South", "Ohafia", "Umuahia North", "Umuahia South"] },
  { state: "Adamawa", areas: ["Demsa", "Fufore", "Ganye", "Girei", "Hong", "Mubi North", "Mubi South", "Numan", "Yola North", "Yola South"] },
  { state: "Akwa Ibom", areas: ["Abak", "Eket", "Etinan", "Ikot Ekpene", "Itu", "Oron", "Uyo"] },
  { state: "Anambra", areas: ["Aguata", "Awka North", "Awka South", "Dunukofia", "Ihiala", "Nnewi North", "Nnewi South", "Onitsha North", "Onitsha South"] },
  { state: "Bauchi", areas: ["Azare", "Bauchi", "Bogoro", "Dass", "Jama'are", "Katagum", "Misau", "Ningi", "Toro"] },
  { state: "Bayelsa", areas: ["Brass", "Ekeremor", "Kolokuma/Opokuma", "Nembe", "Ogbia", "Sagbama", "Southern Ijaw", "Yenagoa"] },
  { state: "Benue", areas: ["Gboko", "Guma", "Gwer East", "Katsina-Ala", "Makurdi", "Otukpo", "Vandeikya"] },
  { state: "Borno", areas: ["Bama", "Biu", "Dikwa", "Gwoza", "Jere", "Konduga", "Maiduguri", "Monguno"] },
  { state: "Cross River", areas: ["Akamkpa", "Bakassi", "Biase", "Calabar Municipality", "Calabar South", "Ikom", "Obudu", "Ogoja"] },
  { state: "Delta", areas: ["Abraka", "Agbor", "Asaba", "Bomadi", "Burutu", "Ethiope East", "Sapele", "Ughelli North", "Warri North", "Warri South"] },
  { state: "Ebonyi", areas: ["Abakaliki", "Afikpo North", "Afikpo South", "Ezza North", "Ezza South", "Ikwo", "Ishielu", "Ohaukwu"] },
  { state: "Edo", areas: ["Akoko-Edo", "Benin City", "Egor", "Esan Central", "Esan West", "Ikpoba-Okha", "Oredo", "Uhunmwonde"] },
  { state: "Ekiti", areas: ["Ado Ekiti", "Efon", "Ekiti East", "Ekiti South-West", "Ikere", "Ikole", "Irepodun/Ifelodun", "Oye"] },
  { state: "Enugu", areas: ["Awgu", "Enugu East", "Enugu North", "Enugu South", "Nsukka", "Oji River", "Udi", "Uzo-Uwani"] },
  { state: "Abuja (FCT)", areas: ["Abaji", "Apo District", "Asokoro", "Bwari", "Central Area", "Garki", "Gudu", "Guzape District", "Gwagwalada", "Jabi", "Kado", "Karu", "Katampe", "Kubwa", "Kuje", "Lugbe", "Maitama", "Utako", "Wuse 2"] },
  { state: "Gombe", areas: ["Akko", "Balanga", "Billiri", "Dukku", "Gombe", "Kaltungo", "Kwami", "Yamaltu/Deba"] },
  { state: "Imo", areas: ["Ideato North", "Ideato South", "Ikeduru", "Mbaitoli", "Mbaise", "Ngor Okpala", "Orlu", "Owerri Municipal", "Owerri North", "Owerri West"] },
  { state: "Jigawa", areas: ["Birnin Kudu", "Dutse", "Gumel", "Hadejia", "Kazaure", "Ringim", "Sule Tankarkar"] },
  { state: "Kaduna", areas: ["Chikun", "Igabi", "Jema'a", "Kaduna North", "Kaduna South", "Kafanchan", "Kachia", "Soba", "Zaria"] },
  { state: "Kano", areas: ["Dala", "Fagge", "Gwale", "Kano Municipal", "Kumbotso", "Nasarawa", "Tarauni", "Ungogo", "Wudil"] },
  { state: "Katsina", areas: ["Daura", "Dutsin-Ma", "Funtua", "Kankia", "Katsina", "Malumfashi", "Mani"] },
  { state: "Kebbi", areas: ["Argungu", "Bagudo", "Birnin Kebbi", "Bunza", "Jega", "Koko/Besse", "Yauri", "Zuru"] },
  { state: "Kogi", areas: ["Ajaokuta", "Ankpa", "Dekina", "Idah", "Kabba/Bunu", "Lokoja", "Okene", "Omala"] },
  { state: "Kwara", areas: ["Asa", "Baruten", "Edu", "Ilorin East", "Ilorin South", "Ilorin West", "Offa", "Oyun"] },
  { state: "Lagos", areas: ["Agege", "Ajah", "Alimosho", "Amuwo Odofin", "Apapa", "Badagry", "Epe", "Eti-Osa", "Ibeju-Lekki", "Ikeja", "Ikorodu", "Ikoyi", "Kosofe", "Lagos Island", "Lagos Mainland", "Lekki Phase 1", "Maryland", "Mushin", "Surulere", "Victoria Island", "Yaba"] },
  { state: "Nasarawa", areas: ["Akwanga", "Doma", "Karu", "Keffi", "Lafia", "Nasarawa", "Toto", "Wamba"] },
  { state: "Niger", areas: ["Agaie", "Bida", "Bosso", "Kontagora", "Lapai", "Minna", "Suleja", "Tafa", "Wushishi"] },
  { state: "Ogun", areas: ["Abeokuta North", "Abeokuta South", "Ado-Odo/Ota", "Ijebu Ode", "Ikenne", "Obafemi Owode", "Sagamu", "Yewa South"] },
  { state: "Ondo", areas: ["Akure North", "Akure South", "Idanre", "Ikare Akoko", "Ilaje", "Ondo East", "Ondo West", "Owo"] },
  { state: "Osun", areas: ["Ede North", "Ejigbo", "Ife Central", "Ife East", "Ilesa East", "Ilesa West", "Iwo", "Osogbo"] },
  { state: "Oyo", areas: ["Afijio", "Akinyele", "Egbeda", "Ibadan North", "Ibadan North-East", "Ibadan South-West", "Iseyin", "Ogbomosho North", "Oyo East"] },
  { state: "Plateau", areas: ["Barkin Ladi", "Bassa", "Bokkos", "Jos East", "Jos North", "Jos South", "Langtang North", "Mangu", "Pankshin"] },
  { state: "Rivers", areas: ["Bonny", "Eleme", "Obio-Akpor", "Okrika", "Omuma", "Oyigbo", "Port Harcourt", "Tai"] },
  { state: "Sokoto", areas: ["Bodinga", "Gwadabawa", "Illela", "Kebbe", "Sokoto North", "Sokoto South", "Tambuwal", "Wamakko"] },
  { state: "Taraba", areas: ["Bali", "Donga", "Gashaka", "Ibi", "Jalingo", "Takum", "Wukari", "Zing"] },
  { state: "Yobe", areas: ["Damaturu", "Fika", "Gashua", "Geidam", "Nguru", "Potiskum", "Yunusari"] },
  { state: "Zamfara", areas: ["Anka", "Bungudu", "Gusau", "Kaura Namoda", "Maradun", "Talata Mafara", "Tsafe", "Zurmi"] },
];
