export const STATE_CODES: Record<string, string> = {
  "Federal Capital Territory": "ABJ",
  "Abuja (FCT)": "ABJ",
  "FCT": "ABJ",
  Abuja: "ABJ",
  Abia: "ABI",
  Adamawa: "ADA",
  "Akwa Ibom": "AKW",
  Anambra: "ANA",
  Bauchi: "BAU",
  Bayelsa: "BAY",
  Benue: "BEN",
  Borno: "BOR",
  "Cross River": "CRS",
  Delta: "DEL",
  Ebonyi: "EBO",
  Edo: "EDO",
  Ekiti: "EKT",
  Enugu: "ENU",
  Gombe: "GOM",
  Imo: "IMO",
  Jigawa: "JIG",
  Kaduna: "KAD",
  Kano: "KAN",
  Katsina: "KAT",
  Kebbi: "KEB",
  Kogi: "KOG",
  Kwara: "KWA",
  Lagos: "LAG",
  Nasarawa: "NAS",
  Niger: "NIG",
  Ogun: "OGN",
  Ondo: "OND",
  Osun: "OSU",
  Oyo: "OYO",
  Plateau: "PLA",
  Rivers: "RIV",
  Sokoto: "SOK",
  Taraba: "TAR",
  Yobe: "YOB",
  Zamfara: "ZAM",
};

export function getStateCode(state: string): string {
  return STATE_CODES[state] ?? state.toUpperCase().slice(0, 3);
}
